### PR TITLE
Add ICS-23 proofs

### PR DESCRIPTION
**Pull request by mkaczanowski**
cc: @lightyear15

### CODE REVIEW

**Review by lightyear15 — APPROVED** [review]
noice!!
approving it
P.S. you can probably optimize ``tmProofSpec`` a bit.
I think if you declare it as constant you'll be able to save some gas at runtime

**Comment by mkaczanowski** [comment]
afaik there is no way to define constant struct yet: https://github.com/ethereum/solidity/issues/4037

**Comment by lightyear15** [comment]
https://docs.soliditylang.org/en/v0.8.2/cheatsheet.html#modifiers

**Comment by mkaczanowski** [comment]
That's best I can do for now:
https://github.com/ChorusOne/tendermint-sol/pull/20

Tried constant, but here's the error:
```
 DeclarationError: Constants of non-value type not yet implemented.
 ProofSpec.Data private constant _TM_PROOF_SPEC = ProofSpec.Data({
```

**Pull request merged**
